GRANT SELECT, INSERT, UPDATE, DELETE ON phpmyadmin.* TO 'site-user'@'localhost' IDENTIFIED BY 'root';
GRANT ALL PRIVILEGES ON *.* TO 'site-user'@'localhost' IDENTIFIED BY 'root' WITH GRANT OPTION;

CREATE DATABASE wordpress;
FLUSH PRIVILEGES;